### ISSUE TITLE
Create sub-cluster networking catalog for multi-tenant type

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#103]
As part of building out the sub-cluster implementation in the multi-tenant type, a sub-cluster networking catalog for all will need to be created which will apply network definitions and configurations.

The subcluster networking catalog contains the networking definitions for all subclusters.  Each subcluster's networking definitions are listed sequentially in this catalog and contain information specific to the subcluster, such as:

kubernetes (e.g., service & Pod CIDRs, control plan endpoints, API server certificate SANs)
port range - ensure that port range in a subcluster does not overlap with a port range for any other subcluster
exposed services (e.g., service name, node port, target port, protocol)
 
Acceptance Criteria: Demonstrate that these network configurations are successfully applied to each sub-cluster on VMs in a sample multi-tenant deployment

**Comment by ak3216** [comment]
https://gerrit.mtn5.cci.att.com/c/nc-release/+/90141/2/manifests/type/cloud-harbor/shared/catalogues/subcluster-networking.yaml < this is a downstream model upon which the catalog can be based.

**Comment by eratnch** [comment]
I can start on this if nobody else already has. Please let me know. Thanks!

**Comment by lb4368** [comment]
@eratnch  - You are assigned.  Thanks!

**Comment by mf4716** [comment]
@eratnch - Ratnopam, is there an updated status?

**Comment by eratnch** [comment]
Hi @mf4716, I created a [PS](https://review.opendev.org/c/airship/treasuremap/+/779889) for this.

**Comment by eratnch** [comment]
@ak3216, PS https://review.opendev.org/c/airship/treasuremap/+/779889 is ready for review.
