### ISSUE TITLE
Deploy Virtual Node Operator (ViNO) via Airship Phase in multi-tenant type

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#104]
**Problem description**
As an operator, I want to deploy the Virtual Node Operator (ViNO) as part of a multi-tenant site during an airshipctl phase, so that there is support for defining sub-clusters in later phase(s).

**Proposed change**
This involves delivering ViNO CRD/operator to the target/management cluster as part of an airshipctl phase (possibly initinfra). Upon completion of this phase the operator is deployed and ready for use. These CRDs/Operators are the critical components in deploying the sub-clusters to their desired state.

1. Integrate the delivery of the ViNO CRD/operator (https://opendev.org/airship/vino) into an Airship phase defined in the multi-tenant type manifests.
2. Verify capability to run phase applying ViNO CRD/operator via Airship as part of a Cloud Harbor site deployment leveraging the Cloud Harbor type manifests.

**Comment by digambar15** [comment]
Please assign this issue to me.

**Comment by ak3216** [comment]
@digambar15 all yours, please let us know t-shirt size so we can add. Thanks.

**Comment by digambar15** [comment]
PS Created https://review.opendev.org/c/airship/treasuremap/+/781228. Got +2 from matt and +1 from Ian.

**Comment by lb4368** [comment]
New PSs merged:  https://review.opendev.org/c/airship/treasuremap/+/783223 and https://review.opendev.org/c/airship/treasuremap/+/787406.  Closing
