### ISSUE TITLE
Deliver Support Infra Provider (SIP) Cluster CRD/Operator via Airship Phase in multi-tenant Type

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#105]
**Problem description**
As an operator, I want to deploy the SIP Operator as part of a multi-tenant site during an airshipctl phase, so that there is support for defining sub-clusters in later phase(s).

**Proposed change**
This involves delivering SIP CRD/operator to the target/management cluster as part of an airshipctl phase (possibly initinfra).  Upon completion of this phase the operator is deployed and ready for use. These CRDs/Operators are the critical components in deploying the sub-cluster to its desired state.

1. Integrate the delivery of the SIP CRD/operator (https://opendev.org/airship/sip) into an Airship phase defined in the multi-tenant type manifests.
2. Verify capability to run phase applying SIP CRD/operator via Airship as part of a multi-tenant site deployment leveraging the multi-tenant type manifests.

**Comment by drewwalters96** [comment]
Still in need of reviews:

https://review.opendev.org/c/airship/treasuremap/+/779517
https://review.opendev.org/c/airship/treasuremap/+/779518
https://review.opendev.org/c/airship/treasuremap/+/780121
https://review.opendev.org/c/airship/treasuremap/+/779519/
