### ISSUE TITLE
Update to latest airshipctl reference

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/treasuremap#108]
The current airshipctl reference is two weeks old, and the documents in treasuremap are no longer compatible with the master branch of Airshipctl. We need to advance this reference and correct any document issues to take advantage of the newest airshipctl features and exported functions.

**Comment by jezogwza** [comment]
discussing if issue https://github.com/airshipit/treasuremap/issues/100 was suppose to solve this

**Comment by drewwalters96** [comment]
The pinned [commit](https://github.com/airshipit/treasuremap/blob/v2/zuul.d/jobs.yaml#L70) is from [21 days ago](https://github.com/airshipit/airshipctl/tree/5820e22d9f436df2f93d8b71286b2ad0492279bc)

**Comment by ak3216** [comment]
https://review.opendev.org/c/airship/treasuremap/+/778728 has merged, can we close this?

**Comment by ak3216** [comment]
Closing per merge of https://review.opendev.org/c/airship/treasuremap/+/778728
