### ISSUE TITLE
Fix ingress function implementation

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/treasuremap#109]
We have an ingress function in Treasuremap and another ingress function in airshipctl. The ingress function in airshipctl is not considered to be production-ready and is intended for gating patches in that repository. Yet, we deploy that function in treasuremap and ignore the function defined here.

We need to fix the [airship-core/target/workload entrypoint](https://github.com/airshipit/treasuremap/blob/v2/manifests/type/airship-core/target/workload/kustomization.yaml) to use the Treasuremap ingress function and define the appropriate replacements.

NOTE: There is a [stray entrypoint](https://github.com/airshipit/treasuremap/blob/v2/manifests/type/airship-core/target/workload/ingress/kustomization.yaml) for the Treasuremap ingress function that should also be removed.

**Comment by manojkva** [comment]
Please assign it to me.

**Comment by manojkva** [comment]
Review PS = https://review.opendev.org/c/airship/treasuremap/+/782473

**Comment by manojkva** [comment]
This could be closed. PS = https://review.opendev.org/c/airship/treasuremap/+/782473 merged.

**Comment by ak3216** [comment]
@manojkva, closing it per your comment. In the future if you add `Closes: xxx` where xxx is the issue number, the Airshipbot will close it automatically on merge. Thanks!
