### ISSUE TITLE
Deliver Grafana helm charts (Helm Operator)

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#11]
**Problem description**
To support software stack deployment, leverage Helm Operator to deliver helm charts with the correct configuration for Grafana.

**Proposed change**
Utilize functionality being developed in airshipit/airshipctl#177 to deliver Helm charts.

**Potential impacts**
This would change the delivery mechanism from Argo/Armada to Helm Operator need to make sure potential sequencing gaps are handled.

**Comment by seaneagan** [comment]
Iniitial analysis of feature parity of stable grafana chart with osh-infra grafana chart:

Gaps:

1. Unclear how to add below jobs. Which ones are still needed? Can be included in separate chart? Can be included in grafana kustomize function (kustomize should generate unique names for jobs each time?)?
a. db init
b. db session sync
c. set admin user
d. add home dashboard

2. helm test framework is `bats` based, integrating selenium tests would require creating/maintaining image with bats+selenium and rewriting selenium tests using bats. 

Advantages:

1. Distributed definition of dashboards via creating configmap for each:
    a. can list configmaps explicitly in grafana values.yaml or
    b. can enable "dashboard sidecar" to auto discover them via labels
    c. delivery:
      i. include dashboard for component inside component's function
      ii. standalone dashboard functions, and possibly dashboard group functions

**Comment by lb4368** [comment]
Blocked by #26

**Comment by lb4368** [comment]
Dependent issue #26  is closed so removing blocked label.
