### ISSUE TITLE
True up treasuremap base version catalog

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#112]
**Problem description (if applicable)**
There may be additional image references in the manifests which do not have entries in the versions catalog. We need to true up the catalog to account for any missing images.

**Proposed change**
- Search for all the images in use in the manifests.
- Compare against the https://github.com/airshipit/airshipctl/blob/master/manifests/function/airshipctl-base-catalogues/versions-airshipctl.yaml catalog & https://github.com/airshipit/treasuremap/blob/v2/manifests/function/treasuremap-base-catalogues/versions-treasuremap.yaml to find any delta not accounted for already by the airshipctl base versions catalog & the existing treasuremap base catalog.
- This should be a follow on to https://github.com/airshipit/airshipctl/issues/498 which will true up airshipctl
- Add any missing entries to the catalog
- Change the kind to VersionCatalogue & ensure that the format of the catalog will pass [VersionsCatalogue schema](https://github.com/airshipit/airshipctl/blob/master/manifests/function/airshipctl-schemas/versions-catalogue.yaml) validation defined in Airshipctl. This does have a dependency on https://github.com/airshipit/airshipctl/issues/511

**Comment by matthew-fuller** [comment]
Please assign this to me.

**Comment by matthew-fuller** [comment]
Treasuremap branches have changed, so a new change has been opened for this issue against the master branch: https://review.opendev.org/c/airship/treasuremap/+/786884

**Comment by matthew-fuller** [comment]
This change (786884) is essentially ready for review, but it's dependent on [this](https://review.opendev.org/c/airship/airshipctl/+/784620) change in airshipctl landing first, so the validate_docs job will continue to fail until the AIRSHIPCTL_REF is updated to pull in the schema changes.
