### ISSUE TITLE
Add github issue templates

### ISSUE THREAD

**Issue by seaneagan** [airshipit/treasuremap#115]
This will help drive up the quality of github issues by including issue labels (triage, enhancement, bug) and other relevant context.

This will be necessary for example to ensure we can generate quality release notes (#113).

**Comment by ak3216** [comment]
@seaneagan they were there, but I think @jezogwza 's patchset with them didn't merge so there's several projects where this fell off including AirshipUI, Charts & hostconfig-operator. SIP, ViNO & Images still had the templates as of Wednesday, but I've not checked them since.

**Comment by lb4368** [comment]
There is @jezogwza patchset here related to this:  https://review.opendev.org/c/airship/treasuremap/+/778508

**Comment by seaneagan** [comment]
https://review.opendev.org/c/airship/treasuremap/+/783742
