### ISSUE TITLE
Define phase to apply Calico network policies

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#119]
Define a custom phase for the airship-core type to implement the Calico network policies defined in #43. It should use the generic container leveraging calicoctl being defined in https://github.com/airshipit/airshipctl/issues/494.

**Comment by eratnch** [comment]
Please assign this issue to me. Thanks.

**Comment by eratnch** [comment]
PS https://review.opendev.org/c/airship/treasuremap/+/786905 is ready for review.
Thanks!
