### ISSUE TITLE
VRRP Cleanup

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#121]
To correct the issue raised on VRRP seems to be from the json6902patch merge construct. 
The below attributes to be added to the preKubeadmCommands as a part of the list but it has ended up concatenating both the lines which is leading to the issue.

- op: add
  path: "/spec/kubeadmConfigSpec/preKubeadmCommands/-"
  value:
      apt-get update && apt-get install -y bridge-utils keepalived ipset ipvsadm
      systemctl enable --now keepalived

The fix is to put and additional add op for the second line like below.
- op: add
  path: "/spec/kubeadmConfigSpec/preKubeadmCommands/-"
  value:
      apt-get update && apt-get install -y bridge-utils keepalived ipset ipvsadm
- op: add
  path: "/spec/kubeadmConfigSpec/preKubeadmCommands/-"
  value:
      systemctl enable --now keepalived

Also remove the apt-get install/update as it should be addressed in [image builder #10](https://github.com/airshipit/images/issues/10) . This needs to be remove this line as part of the fix.

**Comment by manojkva** [comment]
Please assign this to me

**Comment by ak3216** [comment]
@manojkva done

**Comment by mf4716** [comment]
For documentation only - Manoj's PS is https://review.opendev.org/c/airship/treasuremap/+/784790

**Comment by manojkva** [comment]
Can be closed as the fix is merged.

**Comment by ak3216** [comment]
Closing per merge
