### ISSUE TITLE
Clean up catalogues by selector

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/treasuremap#125]
Alexey took advantage of some new Kustomize functionality to simplify the way that we clean up catalogues after they're used in transformer kustomizations (e.g. secret generator, host generator...), deleting them via rules in a shared function which can delete resources by `kind:`.
https://review.opendev.org/c/airship/airshipctl/+/779829

This issue is to model the changes above into the treasuremap project.  This will greatly simplify per-site and per-type kustomize boilerplate clutter.

1. Create a treasuremap/manifests/function/treasuremap-cleanup function, which extends airshipctl's airshipctl-cleanup function, and which adds in a PatchTransformer for all additional catalogue kinds defined in Treasuremap.

2. Replace all the /cleanup entrypoints with a kustomization on top of the treasuremap-cleanup function, following the pattern defined in Alexey's airshipctl change.

**Comment by mattmceuen** [comment]
Just chatted with Alexey Odinokov, he is interested in implementing this one (I'll assign it to him after he comments on this)

**Comment by aodinokov** [comment]
@mattmceuen , I can take it

**Comment by aodinokov** [comment]
WIP: https://review.opendev.org/c/airship/treasuremap/+/787276

**Comment by aodinokov** [comment]
This has been merged. can be closed

**Comment by ak3216** [comment]
closing per code merge
