### ISSUE TITLE
Update Dex Image to >= 2.26.0 : Critical Security Vulnerability

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/treasuremap#126]
**Describe the bug**
We currently use version v2.20.0 of the Dex image, which contains a critical security vulnerability. The [recommended mitigation](https://github.com/dexidp/dex/security/advisories/GHSA-m9hp-7r99-94h5) is to update to a version > `2.26.0`.

It's not known if this will require chart updates or not. If so, an issue should be filed against airship/charts.

**Comment by sshiba** [comment]
Updated helm charts to use dex v2.26.0 image tag

**Comment by sshiba** [comment]
The PS https://review.opendev.org/c/airship/charts/+/785540 updates the dex image tag to v2.28.1, which is currently in review.

**Comment by sshiba** [comment]
The PS https://review.opendev.org/c/airship/charts/+/785540 has been merged, which updates the dex image tag to v2.28.1

**Comment by lb4368** [comment]
Closed per patchset merge with Dex image update
