### ISSUE TITLE
Provide Encryption for External Password for LDAP Backend for Dex

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#128]
**Problem description (if applicable)**
When configuring and LDAP back-end for the Dex OIDC provider (#19), the LDAP credentials must be included in the configuration that is applied to the target server.  These provided credentials must be stored/encrypted such that there no access to the clear text password during site deployment. 

**Proposed change**
Provide a mechanism to securely provide external LDAP credentials to a site build in such a way that can be used to provide the values to the Dex configuration when applied to a cluster during airshipctl phase.

**Comment by sshiba** [comment]
Alexey is working on the feature providing the encryption for external passwords. After this feature is merged I can apply it to the LDAP password.

**Comment by aodinokov** [comment]
https://review.opendev.org/c/airship/treasuremap/+/790512 has been merged. 

the needed replacement was introduced there: https://review.opendev.org/c/airship/treasuremap/+/790512/33/manifests/function/dex-aio/replacements/update-dex.yaml

**Comment by sshiba** [comment]
Encrypted the password provided for LDAP test itservices in https://review.opendev.org/c/airship/treasuremap/+/791835/

**Comment by sshiba** [comment]
https://review.opendev.org/c/airship/treasuremap/+/791835 is ready for review. Just waiting for zuul to pass first.

**Comment by sshiba** [comment]
PS https://review.opendev.org/c/airship/treasuremap/+/791835 has been merged completing this issue.
