### ISSUE TITLE
Deploy base multi-tenant type site in STL3

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#129]
Once issue #132 has been completed & the multi-tenant type has be derived from the airship-core reference type, we want to deploy the multi-tenant type site in STL3 before adding in the sub-cluster components. This ensure that the base multi-tenant type deploys successfully and will also allow for making any necessary changes to the CI/CD pipeline to deploy the multi-tenant type site alongside the airship-core type site on an ongoing basis.

**Comment by imarijitbose** [comment]
Assigning to me.

**Comment by imarijitbose** [comment]
This is been verified once in the stl3. Pending PS for this : https://review.opendev.org/c/airship/treasuremap/+/790795

**Comment by imarijitbose** [comment]
The issue has been verified once more at the current tip of treasuremap master and pinned airshipctl.
Traesuremap hash: e0a44391f2eeefa74d053ee0fd51a9edfb6f62f2
airshictl : c355b600d7a3fd66f03016ad9384a13cf17e80e7

Requesting close of this issue.

**Comment by ak3216** [comment]
Closing per above

**Comment by imarijitbose** [comment]
The airshpctl hash was mentioned wrong. correct hash : e12b1e2fa639e02a54cb982d372dcdd8e3ee39de
