### ISSUE TITLE
Deploy multi-tenant type site with sub-cluster in STL labs

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#130]
Building on #129, we want to define a multi-tenant type reference site which includes a sub-cluster deployment in the STL labs. This is will include, but may not be limited to the following:

- All of the SIP/ViNO integration into Treasuremap - #103, #104, #105, #106, #123 - completed
- #94 - completed
- #82 - completed
- #122 - complete
- Deploying sample (WordPress) sub-cluster - #107 - completed
- Deploying LMA sub-cluster - #150 (in progress) & #118 (complete)
- Calico Policies - #119 to define phase for delivering Calico policies - completed & #131 network policies for infra & sub-clusters - completed
- #139 
- #140 
- #177 
- #172 
- #170 
- #169
- #168 
- #160 

Resolve any bugs encountered during implementation:
- #189
- #185
- #183 
- #182 
- #181 
- #180
- #178

Dex (not critical path for sub-cluster delivery)
- #128 
- #134 
- #135
- #136 

Semi-related, needed for gating & stability
- #166 
- #176

**Comment by lb4368** [comment]
Some of the tasks for the sub-cluster deployments are:

1.	Create phase plans to deploy the LMA and WordPress sub-clusters
2.	Create scripts to deliver SIP/ViNO phases and subcluster phase plans
3.	Update SIP to the latest version and configure the recently added infrastructure services.
 
Below are patchsets from @drewwalters96 that may help someone to complete these tasks.

https://review.opendev.org/c/airship/treasuremap/+/788042
https://review.opendev.org/c/airship/treasuremap/+/788080
https://review.opendev.org/c/airship/treasuremap/+/788029/3

**Comment by imarijitbose** [comment]
Assigning to me.

**Comment by lb4368** [comment]
Closing this issue as sub-cluster delivery intent has been met.  Residual items open for possible future enhancement
