### ISSUE TITLE
Create network policies (N/S and E/W) for infrastructure and sub-clusters

### ISSUE THREAD

**Issue by onlysource** [airshipit/treasuremap#131]
**Problem description (if applicable)**
The deployment phase will need to implement specific N/S and E/W policies to allow all intended traffic flow between Infrastructure and Sub-clusters

**Proposed change**
Create necessary network policies to support desired traffic flow within the site. These policies will be implemented via 'airshipctl' phase.

**Potential impacts**
Not having any network policies could potentially overwhelm the infrastructure network from undesired traffic (N/S or E/W), leading to service-denial.

**Comment by eratnch** [comment]
Please assign to me, size m.

**Comment by eratnch** [comment]
Updated PS at https://review.opendev.org/c/airship/treasuremap/+/789942.
Thanks.
