### ISSUE TITLE
Deploy airship-core type site in STL3

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#132]
Need to create a CI/CD job which can be used to deploy and validate the reference airship-core type site built for v2.0 in the STL3 lab from the treasuremap master branch.

This will require pulling in patchsets from the v2.0 branch that are not yet merged.

**Comment by lb4368** [comment]
The following patchsets cherry pick changes from v2.0 branch:

https://review.opendev.org/c/airship/treasuremap/+/788549
https://review.opendev.org/c/airship/treasuremap/+/788548
https://review.opendev.org/c/airship/treasuremap/+/788517
https://review.opendev.org/c/airship/treasuremap/+/788576
https://review.opendev.org/c/airship/treasuremap/+/788575
https://review.opendev.org/c/airship/treasuremap/+/787388
https://review.opendev.org/c/airship/treasuremap/+/788546
https://review.opendev.org/c/airship/treasuremap/+/788545
https://review.opendev.org/c/airship/treasuremap/+/788554

**Comment by lb4368** [comment]
This issue is probably dependent upon merging v2.0 branch patchsets in airshipctl:  https://github.com/airshipit/airshipctl/issues/538

**Comment by imarijitbose** [comment]
Assigning in to me

**Comment by imarijitbose** [comment]
This is been verified with master branch treasuremap (hash: 7743cae6d91923b4c8f6dcd5dc78051abf046991) and pinned version of airshipctl (hash: c355b600d7a3fd66f03016ad9384a13cf17e80e7).

Screen shot attached and this can be closed now
![airship-core](https://user-images.githubusercontent.com/8610555/117907811-0ba67500-b29d-11eb-8b2e-273fc01d8705.JPG)

**Comment by ak3216** [comment]
Closing per evidence above of successful deployment
