### ISSUE TITLE
Create multi-tenant type scripts to deliver SIP/ViNO phases and sub-cluster phase plans

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#140]
To support deploying a site with the multi-tenant type, create a set of deployment scripts separate from the airship-core type which deploys SIP, ViNO, the LMA & Wordpress sub-clusters & their workloads.

One of the tasks in updating the scripts is to ensure SIP code references the latest version and is configured to include the recently added infrastructure services.

Patchset https://review.opendev.org/c/airship/treasuremap/+/788029/3 can be leveraged as a starting point.

**Comment by ian-howell** [comment]
Closed by https://review.opendev.org/c/airship/treasuremap/+/792000
