### ISSUE TITLE
incorrect node labels on worker nodes during bare metal deployment

### ISSUE THREAD

**Issue by rkjain** [airshipit/treasuremap#142]
**Description**
We used v2.0 of airshipctl and treasuremap to create a 6 node cluster (3 CP, 3 Workers)in ericsson lab. The deployment was successful. However, the worker nodes are also labelled as master.

**Steps To Reproduce**
Follow site authoring/deployment guide for baremetal deployment.
```
airship@as2-1-r:~$ sudo kubectl  --kubeconfig /home/airship/.airship/kubeconfig --context target-cluster get nodes
[sudo] password for airship: 
NAME    STATUS   ROLES           AGE     VERSION
bm129   Ready    master          5h25m   v1.18.6
bm130   Ready    master          4h31m   v1.18.6
bm131   Ready    master          4h48m   v1.18.6
bm132   Ready    master,worker   4h8m    v1.18.6
bm133   Ready    master,worker   4h8m    v1.18.6
bm134   Ready    master,worker   4h8m    v1.18.6
```

**Expected behavior**
```
airship@as2-1-r:~$ sudo kubectl  --kubeconfig /home/airship/.airship/kubeconfig --context target-cluster get nodes
[sudo] password for airship: 
NAME    STATUS   ROLES           AGE     VERSION
bm129   Ready    master          5h25m   v1.18.6
bm130   Ready    master          4h31m   v1.18.6
bm131   Ready    master          4h48m   v1.18.6
bm132   Ready    worker   4h8m    v1.18.6
bm133   Ready    worker   4h8m    v1.18.6
bm134   Ready    worker   4h8m    v1.18.6
```

**Comment by imarijitbose** [comment]
This script 35 is causing the master label at the worker nodes.
https://review.opendev.org/plugins/gitiles/airship/treasuremap/+/refs/heads/v2.0/tools/deployment/35_deploy_worker_node.sh#63.  Working to get it corrected

**Comment by sreejithpunnapuzha** [comment]
all commits for this issue can be found with the topic "fix-node-label" and the url for this commit is https://review.opendev.org/q/topic:%22fix-node-label%22+(status:open%20OR%20status:merged)

**Comment by sreejithpunnapuzha** [comment]
The above mentioned commit is merged. Gates are working as expected. hence closing this issue
