### ISSUE TITLE
Uplift ViNO CRD/CR

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#145]
**Problem description**
ViNO CRD and CR used in treasuremap is out-of-date and needs to be uplifted to latest version to take advantage of latest updates to working version.

**Proposed change**
- Update ViNO manifest function (manifests/function/vino) for latest ViNO version
- Update ViNO CR used in workload-config phase/function (manifests/function/workload-config)

**Potential impacts**
At some point we will need to address version management for the images used as part of ViNO (vino controller, vino-builder, libvirt, nodelabeler)

**Comment by teoyaomiqui** [comment]
related patchset https://review.opendev.org/c/airship/treasuremap/+/792682
