### ISSUE TITLE
Generate and Encrypt BMC Credentials for ViNO CR

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#147]
**Problem description**
Currently the BMC credentials specified in the ViNO CR and used for creating BMH resources in the workload-config manifest function are hard-coded to clear text values.  These credentials need to be properly secured and managed during multi-tenant type deployments.

**Proposed change**
As part of multi-tenant site deployment, provide capability to generate and encrypt the BMC credentials to be used for BMH resources generated by ViNO CR so that these credentials are properly secured and are never stored unencrypted in manifests.

**Comment by sirajyasin** [comment]
@lb4368 , I can start working on this issue if no one has started yet.
