### ISSUE TITLE
Use KPT to update Ceph function manifests

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/treasuremap#152]
**Problem description (if applicable)**
[KPT](https://googlecontainertools.github.io/kpt/) allows us to pull manifests from git repositories and push them as Treasuremap functions with a single command. This makes Treasuremap function uplifts easier and less error-prone. The Ceph function does not yet use KPT and should be updated to use it.

**Proposed change**
Use KPT to manage Ceph function manifests. Example: [SIP](https://github.com/airshipit/treasuremap/tree/master/manifests/function/sip)

**Comment by sirajyasin** [comment]
@drewwalters96 , I assume this issue is addressed in this [PS](https://review.opendev.org/c/airship/treasuremap/+/796097). Could you please advice if this can be marked closed or is there any additional work on this issue ?

**Comment by drewwalters96** [comment]
@sirajyasin Agreed, thank you.
