### ISSUE TITLE
Remove Storage Cluster from Virtual Site Deployments

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#153]
**Problem description**
The Zuul gates which do the virtual site deployments have been failing often with timeouts.  It is believed that some of this may be related to the Rook deployment of the Ceph storage cluster using too many resources within the virtual environments.  It is suggested to remove the storage cluster composite deployment from the virtual test sites.  The storage cluster deployment would remain in the reference baremetal site deployments.

**Proposed change**
This patchset (https://review.opendev.org/c/airship/treasuremap/+/792694) makes the storage cluster composite deployment a part of the target workload phase for both the _airship-core_ and _multi-tenant_ types.  Once merged, this makes the storage cluster deployment a part of any site inheriting one of these types.  We are requesting that target workload phase for the virtual sites (_test-site_ and _virtual-network-cloud_) overrides the type setting to omit the deployment of the storage cluster (`manifests/composite/storage-cluster`).

The storage-cluster composite needs to continue to be deployed as part of the baremetal reference sites.

**Comment by SirishaGopigiri** [comment]
Please assign this to me

**Comment by SirishaGopigiri** [comment]
Size would be 'M'
