### ISSUE TITLE
Rename Virtual Sites in Treasuremap

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#154]
**Problem description**
The current names for the virtual sites in treasuremap (_test-site_ and _virtual-network-cloud_) are not following a similar naming convention as the baremetal reference sites (_reference-airship-core_ and _reference-multi-tenant_) which identifies the site purpose and its associated site type.

**Proposed change**
Rename the virtual sites in treasuremap as follows to indicate virtual sites associated to specific types:

- test-site --> virtual-airship-core
- virtual-network-cloud --> virtual-multi-tenant

**Comment by sreejithpunnapuzha** [comment]
Commit with changes pushed.. https://review.opendev.org/c/airship/treasuremap/+/793194

**Comment by sreejithpunnapuzha** [comment]
Above change is depend on uplifting airshipctl reference on treasuremap. we need this change to be applied https://review.opendev.org/c/airship/airshipctl/+/792836. once airshipctl is uplifted in treasuremap, recheck zuul job and it should be success

**Comment by sirajyasin** [comment]
test-site --> virtual-airship-core is addressed in this PS and the same is merged
https://review.opendev.org/c/airship/treasuremap/+/795589

**Comment by sreejithpunnapuzha** [comment]
Both sites have been renamed in ps https://review.opendev.org/c/airship/treasuremap/+/795589 and https://review.opendev.org/c/airship/treasuremap/+/793194. hence closing this issue
