### ISSUE TITLE
Align Treasuremap with recent Airshipctl changes

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#159]
Once again the airshipctl reference is out-of-date.  Current AIRSHIPCTL_REF is e12b1e2fa639e02a54cb982d372dcdd8e3ee39de.  Need to update the airshipctl reference in order to support SIP and ViNO deployments.

**Comment by sirajyasin** [comment]
I can work on this issue. can someone assign this to me

**Comment by sirajyasin** [comment]
The related [PS](https://review.opendev.org/c/airship/treasuremap/+/793651) is merged and this issue can be closed
