### ISSUE TITLE
Move lma-stack contents to the workload phase

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/treasuremap#160]
Today, LMA components are deployed in an `lma-stack` phase, which is not what we want.  This issue is to
1) Move the contents of the lma-stack phase to the workload phase of the airship-core type (only)
    Note: the multi-tenant type deploys LMA via a subcluster's workload phase already, which is what we want.
2) Delete the lma-stack phase from all sites/types

**Comment by StevTheDev** [comment]
Assign to me, please.

[This PS](https://review.opendev.org/c/airship/treasuremap/+/793106) handles this for the airship-core type. Trying to shake out some issues with the gate 👍

**Comment by ak3216** [comment]
@StevTheDev all yours. Thanks!

**Comment by ak3216** [comment]
Closing per code merges.
