### ISSUE TITLE
Run CNCF conformance testing in STL labs

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#165]
Run CNCF conformance testing against the reference sites in STL labs (multi-tenant & airship-core).

**Comment by eratnch** [comment]
Please assign this to me. Thanks.

**Comment by eratnch** [comment]
The link to the Jenkins CI pipeline -> https://jenkins.nc.opensource.att.com/job/conformance/job/stl2_Conformance/8/console.

Snippet showing all 277  tests related to conformance pass

![image](https://user-images.githubusercontent.com/66561014/124025799-e261b580-d9be-11eb-9bf9-39e5de273b92.png)

**Comment by ak3216** [comment]
Closing per successful run. Will revisit under a separate issue once the lab has been upgraded to k8s v1.20.
