### ISSUE TITLE
Use `airshipctl plan run` in gates

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#166]
**Proposed change**
In airshipctl (https://github.com/airshipit/airshipctl/issues/517), gates are being updated to use `airshipctl plan run` for deployment.  Once that is complete, this needs to be uplifted in treasuremap gates to replace the scripts that run the individual phases of the deployment.

**Comment by vladiskuz** [comment]
I can start to work on this issue. Can someone assign it to me?

**Comment by vladiskuz** [comment]
PS for the airship-core gating was merged https://review.opendev.org/c/airship/treasuremap/+/795564
PS for the multi-tenant gating is ready for review https://review.opendev.org/c/airship/treasuremap/+/796028

**Comment by mf4716** [comment]
Additional PS from @vladiskuz :  to remove this job - https://review.opendev.org/c/airship/treasuremap/+/797325

**Comment by lb4368** [comment]
This issue is being closed as gating for the airship-core type has been implemented and merged using 'airshipctl plan run'.  Possible future enhancement to apply to multi-tenant gating is tracked via #197.
