### ISSUE TITLE
Align Reference site disk layout for sub-cluster support

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#168]
Need to align the disk configuration for the STL2/STL3 multi-tenant reference site to support sub-clusters as follows:

Host OS: RAID-1, 2 468GB SSDs
Ephemeral Storage for Sub-Clusters: RAID-1, 2 890 GB SSDs
CEPH/Storage: RAID-0, 3 890 GB SSDs

![image](https://user-images.githubusercontent.com/7432527/120844263-c3454480-c534-11eb-9d20-5d8288d927a6.png)

**Comment by mf4716** [comment]
WIP.  2 of 7 (configs/settings) complete as of EOD 6/25.

**Comment by lb4368** [comment]
This is not needed at this time.  Closing.
