### ISSUE TITLE
Create delivery mechanism for sub-cluster QCOW images

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#169]
Building on the work done for delivering the baremetal QCOW image, develop a similar mechanism to deliver sub-cluster VM QCOW images. This should be implemented for the multi-tenant site type & included in the sub-cluster deployment in STL3.

Reference the following merged patchsets: 
https://review.opendev.org/c/airship/airshipctl/+/776705 < Defines delivery mechanism of the qcow image via Ironic. Includes variable catalog updates to reference the qcow image. There are some other updates that removes pre-kubeadm commands that are now contained in the image and others that will likely not be needed for resolving this issue for sub-clusters.
https://review.opendev.org/c/airship/airshipctl/+/779032 < Adds qcow image references & replacements to versions catalog

The sub-cluster image bundle will be defined in this issue:
https://github.com/airshipit/images/issues/20

**Comment by aostapenko** [comment]
https://review.opendev.org/c/airship/airshipctl/+/796484

**Comment by ak3216** [comment]
@aostapenko the above patchset creates the function in airshipctl. Will there also be a PS to include it for use by the multi-tenant type in treasuremap? Sorry if I'm jumping the gun & it's in progress. Thanks.

**Comment by aostapenko** [comment]
I think we can leave cosmetic changes for later. And we'll need to have more discussion on desired layout given specifics of situation we're in.

**Comment by mf4716** [comment]
@aostapenko , it would be a big help to include the Relates-To tag, or Closes tag, in the commit message of your PSs.  This helps us track and correlate the issues-to-PSs.  And, if the Closes tag is used, a bot will automatically close the respective GitHub issue.  Thanks.  https://github.com/airshipit/airshipctl/blob/master/CONTRIBUTING.md#submitting-changes

**Comment by mf4716** [comment]
Abandoned:  https://review.opendev.org/c/airship/airshipctl/+/796484
Replaced by: https://review.opendev.org/c/airship/treasuremap/+/796992

Per Andrii, TM169 can be closed as 796992 merged early morning hrs of 23 June 2021.

**Comment by ak3216** [comment]
Closing per code merge.
