### ISSUE TITLE
Worker nodes should use containerd vs. Docker as default CRI 

### ISSUE THREAD

**Issue by eak13** [airshipit/treasuremap#171]
With https://github.com/airshipit/airshipctl/issues/456 the switch to using containerd as the default CRI was made. While the control plane nodes deployed in Treasuremap appear to have inherited this change, it appears that the worker nodes are still running Docker by default. 

Task:
1. Make any changes to the worker node deployments for both airship-core & multi-tenant type to ensure they implement containerd vs. Docker as the CRI
2. Validate the worker nodes actually deploy using containerd.
3. (Needs discussion) Throw an error if Docker is specified as CRI (it's being deprecated in an upcoming release)

**Comment by matthew-fuller** [comment]
Please assign this to me.

**Comment by ak3216** [comment]
@matthew-fuller all yours

**Comment by matthew-fuller** [comment]
After running the deployment gates locally for treasuremap, I checked the runtime version for nodes 01 and 03, and they both say
```
Container Runtime Version:         containerd://1.4.6
```

I'll need to verify whether Docker was seen on workers using a different deployment method than I used, and if so, try to replicate the problem and make changes if necessary.

**Comment by ak3216** [comment]
@matthew-fuller, if need be, follow up with @aostapenko as he was the one who encountered this during deployment. Thanks.

**Comment by aostapenko** [comment]
This one is already mostly addressed by https://review.opendev.org/c/airship/treasuremap/+/794678 (merged) and https://review.opendev.org/c/airship/airshipctl/+/796380. Though we still need to switch to using airshipctl workers-capm3 replacements and remove workers-capm3 function from TM

**Comment by ak3216** [comment]
@aostapenko I see https://review.opendev.org/c/airship/treasuremap/+/794678 addresses airship-core type, but I didn't see the same for multi-tenant type. Does that still need to be resolved as well?

**Comment by aostapenko** [comment]
multi-tenant type does not currently define workers on type level. Though virtual-network-cloud site (that uses multi-tenant type) is utilizing airshipctl via vm-infra-bridge/dataplane https://review.opendev.org/c/airship/treasuremap/+/794678/5/manifests/function/vm-infra-bridge/dataplane/kustomization.yaml
On the other hand reference-multi-tenant still does not utilize any function and defines all workers resources on site level. Though I believe this should be addressed separately.

**Comment by matthew-fuller** [comment]
The comments so far (and the fact that I wasn't able to reproduce the issue) seem to indicate that most of the work on this issue has already been addressed by the above patch sets. Removing treasuremap's `workers-capm3` function and ensuring all sites and types inherit from airshipctl's instead seems within the scope of this issue, so https://review.opendev.org/c/airship/treasuremap/+/796737 has been created to address this.

**Comment by matthew-fuller** [comment]
Change [796737](https://review.opendev.org/c/airship/treasuremap/+/796737) to remove the `workers-capm3` function from treasuremap has been merged, so this issue can likely be closed now. @lb4368 @aostapenko do you agree?

**Comment by aostapenko** [comment]
+1

**Comment by eak13** [comment]
Closing per above
