### ISSUE TITLE
Update to latest airshipctl reference

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#173]
Until we can put enhanced automation in place, we need to continually align treasuremap with the latest version of airshipctl. We are in a phase of dynamic change & this will be a reoccurring exercise.

**Comment by ak3216** [comment]
https://review.opendev.org/c/airship/treasuremap/+/795201 has been started by @sirajyasin 
 
but it is dependent on https://github.com/airshipit/treasuremap/issues/166  being resolved first

**Comment by jezogwza** [comment]
Automation been taken care of with #161]

**Comment by sirajyasin** [comment]
I am working on the manual uplift while waiting for the automation to be ready.

PS: https://review.opendev.org/c/airship/treasuremap/+/795703

**Comment by sirajyasin** [comment]
Uplift [PS](https://review.opendev.org/c/airship/treasuremap/+/795703)  is merged and this issue can be closed.

**Comment by ak3216** [comment]
Closing this issue per patchset merge. Will open a new issue if we need to resync.
