### ISSUE TITLE
Sub-clusters Deployment: Add Multi-Tenant Cluster Control Plane Nodes to ViNO VM Network

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#177]
**Problem description**
In order for VMs create by a ViNO CR to be provisioned by Ironic, the control plane nodes of the multi-tenant target cluster will need an IP address for the provisioning network for the VMs.

**Proposed change**
Update the target cluster network configuration to define a static IP address for each control plane node of the target cluster on the VM network.

- Provide capability to define a static IP address on the VM network for control plane nodes only
- IP address must be on the same subnet as VM network specified in ViNO CR
- IP address must be outside IP ranges (static and DHCP) reserved for use in the ViNO CR for VM use
- Control plane nodes must have access to VM network for provisioning via Ironic

**Comment by manojkva** [comment]
Please assign this to me. Thanks

**Comment by manojkva** [comment]
As discussed during DSU (21 June 2021), Scope of this issue limited to :  **reference-multi-tenant** site  as the changes for **virtual-network-cloud** site changes will require a separate issue.

**Comment by manojkva** [comment]
PS ready for review https://review.opendev.org/c/airship/treasuremap/+/797244
