### ISSUE TITLE
Sub-clusters Deployment:  Limit vino network cloud-init types to ipv4

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#180]
Ipv4 types in networkData, currently vino network maps to libvirt network, so using type from VINO network isn't reasonable, addressed in (limits us to single ipv4 network, has straight forward to fix in the future, vino will provide different variable for network IP protocol, right now hardcoded by user in network template)

**Environment**
- Treasuremap version: https://github.com/airshipit/treasuremap/commit/12a6940214d4047362d11f8ed1305ce9875a5d57
- Treasuremp site type: multi-tenant

**Comment by lb4368** [comment]
PS:  https://review.opendev.org/c/airship/treasuremap/+/796981

**Comment by teoyaomiqui** [comment]
closing per merged patchset
