### ISSUE TITLE
Sub-clusters Deployment: Sync Sub-Cluster API Server VIP/Port Between SIP CR and Metal3Cluster 

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#181]
The VIP and NodePort used for creation by SIP of the Sub-Cluster API Server load balancer must be the same as specified in the `Metal3Cluster` CR for sub-cluster deployment.  Catalogue replacements need to be set up to provide these same values to both the SIPCluster CR and Metal3Cluster CR for each sub-cluster deployment in treasuremap.

**Environment**
- Treasuremap version: https://github.com/airshipit/treasuremap/commit/12a6940214d4047362d11f8ed1305ce9875a5d57
- Treasuremp site type: multi-tenant

**Comment by ian-howell** [comment]
PS: https://review.opendev.org/c/airship/treasuremap/+/798352
