### ISSUE TITLE
Sub-clusters Deployment: Remove VRRP from Sub-Cluster KCP

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#182]
Since load balancers created by SIP will handle the load balancing for the sub-cluster API servers VRRP is not needed for the associated KubeadmControlPlane resources.  Need to remove VRRP from KCP for sub-clusters.

**Environment**
- Treasuremap version: https://github.com/airshipit/treasuremap/commit/12a6940214d4047362d11f8ed1305ce9875a5d57
- Treasuremp site type: multi-tenant

**Comment by mattmceuen** [comment]
Fix: https://review.opendev.org/c/airship/treasuremap/+/797154

**Comment by lb4368** [comment]
Closing per patchset merge
