### ISSUE TITLE
Sub-clusters Deployment: Need SSH Keys Populated to KubeadmControlPlane 

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#183]
Need to update replacements so that ssh key is populated in KubeadmControlPlane for sub-clusters.  For now, these can be the same ssh key used for the target management cluster

**Environment**
- Treasuremap version: https://github.com/airshipit/treasuremap/commit/12a6940214d4047362d11f8ed1305ce9875a5d57
- Treasuremp site type: multi-tenant

**Comment by seaneagan** [comment]
Actually it looks like the replacements for the control plane ssh authorized keys are already being inherited all the way down into the subclusters from here:
https://github.com/airshipit/airshipctl/blob/master/manifests/function/k8scontrol/replacements/generated-secrets.yaml

For the sub-cluster workers, I created this patchset:
https://review.opendev.org/c/airship/treasuremap/+/797540

**Comment by lb4368** [comment]
Closing per patchset merge
