### ISSUE TITLE
Sub-clusters Deployment: Fix Server/Rack Label Configuration for Multi-Tenant

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#185]
The BMH labels used by ViNO and SIP to identify the server and rack where a VM will be located are inconsistent.  Need to make the label setting consistent across the multi-tenant site deployment.

**Expected behavior**
The chain of events for providing server/rack labels to VMs created by ViNO and consumed by SIP is:
1)  The hostgenerator for the target cluster will need to specify label values for the BMHs.    (https://review.opendev.org/c/airship/airshipctl/+/797130, https://review.opendev.org/c/airship/treasuremap/+/797132)
2)  The synclabeller operator is configured to sync the BMH labels to the K8s nodes
3)  ViNO copies these labels to BMHs for VMs it creates on corresponding k8s nodes.  This is configured in ViNO CR.
4)  SIP scheduling matches to these labels per SIPCluster CR.

Need to align to use the following BMH labels to deliver multi-tenant type sub-cluster:

- `airshipit.org/rack`
- `airshipit.org/server`

**Environment**
- Treasuremap version:  https://github.com/airshipit/treasuremap/commit/12a6940214d4047362d11f8ed1305ce9875a5d57
- Treasuremp site type:  multi-tenant

**Comment by mattmceuen** [comment]
I think I already put in the needed changes for this last week, but they haven't merged:
https://review.opendev.org/c/airship/treasuremap/+/797132
https://review.opendev.org/c/airship/airshipctl/+/797130

**Comment by lb4368** [comment]
Closing per merged patchsets
