### ISSUE TITLE
Links are dead - https://docs.airshipit.org/treasuremap/airsloop.html

### ISSUE THREAD

**Issue by peterwi** [airshipit/treasuremap#188]
Not a bug as such, the docs are not clear, Trying to follow https://docs.airshipit.org/treasuremap/airsloop.html

**Comment by ermurugesanbe** [comment]
Please assignee to me

**Comment by ak3216** [comment]
@ermurugesanbe all yours

**Comment by jezogwza** [comment]
Peter, were you trying to work with Airship 1 specifically, if not please reach out and we can recommend a better approach for diving into Airship 2.

**Comment by peterwi** [comment]
Hi,
Thanks for coming back, I am interested in trying airship for edge, We currently use Openstack but for edge we are looking at something with hyperconverge for storage. I would be interested to know where is a best place to start with airship, from the docs it looked lik airsloop would fit the bill, not sure how can I use airship2.
Many thanks in advance

**Comment by ermurugesanbe** [comment]
> Hi,
> Thanks for coming back, I am interested in trying airship for edge, We currently use Openstack but for edge we are looking at something with hyperconverge for storage. I would be interested to know where is a best place to start with airship, from the docs it looked lik airsloop would fit the bill, not sure how can I use airship2.
> Many thanks in advance

Hi,
I had discussion with team members and airsloop is part of airship1. For your requirement everyone suggest to start with airship2
Full Doc - https://docs.airshipit.org/airshipctl/index.html 
Developer's Guide - https://docs.airshipit.org/airshipctl/developers.html

**Comment by ermurugesanbe** [comment]
Hi @ak3216,
Please close this ticket, this issue fix code has been merged to v1.9 on 12th Jul, @sirajyasin had fixed promote docs issue on below PS.
https://review.opendev.org/c/openstack/project-config/+/804170

**Comment by ak3216** [comment]
Closing per above. Thanks @ermurugesanbe
