### ISSUE TITLE
treasuremap build_image script raises error while running  "airshipctl plan run iso --debug" command

### ISSUE THREAD

**Issue by digambar15** [airshipit/treasuremap#190]
sudo -E SOPS_IMPORT_PGP="$(cat /tmp/key.asc)" SOPS_PGP_FP="FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4" ./tools/deployment/multi-tenant/24_build_images.sh
+ : ../airshipctl
+ cd ../airshipctl
+ ./tools/deployment/24_build_images.sh
+ export USER_NAME=root
+ USER_NAME=root
+ IMAGE_DIR=/srv/images
+ CLEANUP_SERVE_DIR=false
+ SITE=virtual-network-cloud
+ IMAGE_PHASE_PLANS=iso
+ sudo rm -rf /srv/images
+ sudo mkdir -p /srv/images
+ sudo chmod -R 755 /srv/images
+ sudo chown -R root /srv/images
+ unset IFS
+ for plan in $IMAGE_PHASE_PLANS
+ echo 'Build phase plan: iso'
Build phase plan: iso
+ airshipctl plan run iso --debug
[airshipctl] 2021/06/29 11:01:22 opendev.org/airship/airshipctl/pkg/phase/client.go:295: executing phase: iso-cloud-init-data
{"Message":"starting generic container","Operation":"GenericContainerStart","Timestamp":"2021-06-29T11:01:34.217474041Z","Type":"GenericContainerEvent"}
document filtered by selector [Kind="Secret", Namespace="target-infra", Name="node02-network-data"] found no documentsdocument filtered by selector [Kind="Secret", Namespace="target-infra", Name="node02-network-data"] found no documents[airshipctl] 2021/06/29 11:01:36 opendev.org/airship/airshipctl/pkg/events/processor.go:59: Received error on event channel {exit status 1}
Error events received on channel, errors are:
[exit status 1]

**Comment by digambar15** [comment]
Let me know anyone come across any quick fix for above error.

**Comment by jezogwza** [comment]
Is this still happening for you?

**Comment by ak3216** [comment]
@digambar15 is this still occurring?

**Comment by sirajyasin** [comment]
@digambar15 , I was able to run through the deployment script (./tools/deployment/multi-tenant/24_build_images.sh) without any error. Please confirm if you are still experiencing the same issue, so that we can check if something environment specific is causing the issue.

@ak3216 , can you please assign this issue to me. I can work with @digambar15 and help him proceed further.

**Comment by ak3216** [comment]
@sirajyasin all yours.

**Comment by digambar15** [comment]
@sirajyasin @ak3216 - I am not able to reproduce this issue in my recent deployment. Looks like it is fixed. We can close the bug.

**Comment by ak3216** [comment]
Closing per above comment that it currently cannot be reproduced
