### ISSUE TITLE
Upgrade Rook for a brownfield site

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#194]
**Problem description**
In an effort to keep Airship current with the latest updates of its supporting components, upgrade all of the Rook components to the latest supported version.  As part of this effort, we also want to understand the impacts to upgrading Rook in an existing site.

- https://github.com/rook/rook/releases

**Proposed change**

- Update Rook components (storage-cluster, rook-cluster, rook-operator) to the latest version for greenfield deployments
- Identify dependencies and constraints for a Rook upgrade in brownfield deployment
- Provide plan for applying upgrade to existing site
- Identify impacts to cluster availability and performance during an upgrade of existing site

**Comment by shon-phand** [comment]
I can start working on this. Please assign it to me.

**Comment by shon-phand** [comment]
https://hackmd.io/pWo5HfiDQheY3pnVIJgcLQ?view
