### ISSUE TITLE
Spike: Understand Ceph Upgrades (brownfield)

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#195]
**Problem description**
Would like to understand the implications of an upgrade to Ceph in an existing site cluster (brownfield scenario). 

https://docs.ceph.com/en/latest/releases/

**Proposed change**

- Investigate and document a plan for an upgrade of Ceph on an existing cluster
- Identify dependencies and constraints such as Rook versions, etc.
- Identify impacts to cluster availability and performance during an upgrade

**Comment by vs422h** [comment]
Please assign this issue to me.

**Comment by aaronsheffield** [comment]
https://hackmd.io/AnSmSWktSoa7IP74iDEMMg?view
