### ISSUE TITLE
Spike: Determine what happens when a Multus network attachment definition gets changed

### ISSUE THREAD

**Issue by eak13** [airshipit/treasuremap#196]
**Problem description (if applicable)**
Multus provides the ability to connect multiple CNIs to one Kubernetes cluster. Once Multus has been deployed in a network-cloud type (dependent on #20), we want to understand what the impacts of changing the network attachment definitions. 

https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/README.md

**Proposed Change**
 In a running cluster with Multus deployed, with at least 2 NADs defined:
- Perform a configuration change to one of the NADs
- Perform configuration changes to both NADs at the same time

Report back on :
- Impacts to the interface with the changed  NAD. Are there any restart implications? 
- Validate changing one NAD doesn't impact the other NAD defined by Multus
- Any other change considerations

**Comment by digambar15** [comment]
@ak3216  Please assign me.

**Comment by digambar15** [comment]
Design proposal is presented in DEsign meeting and it is also accepted. Can we close this issue as I already started working on developing the feature.

**Comment by digambar15** [comment]
Can we close this issue as I already started the development work ?

**Comment by eak13** [comment]
Closing per above
