### ISSUE TITLE
Create a function to deploy Helm Chart Collator

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#23]
As an operator, I need the ability to deploy helm-chart-collator into the airship-core type so that I can create a helm chart repository in my cluster.

The current lab implementation of helm-chart-collator has a kustomization.yaml file which leverages a namespace.yaml to define the namespace & deployment.yaml to define the daemonset & service. 

If access to the lab implementation is required, please reach out in the Airship slack community & someone should be able to assist.

This has a dependency on #88 to create an image that can then be deployed by HCC.

**Comment by lb4368** [comment]
Blocked by #26

**Comment by lb4368** [comment]
Dependent issue #26  is closed so removing blocked label.

**Comment by sshiba** [comment]
Please, assign this issue to me as I am already working on it as part of Dex support, where Helm collator is used as Helm repository containing the Dex charts.

**Comment by ak3216** [comment]
Please ensure that this is included in the airship-core type deployment

**Comment by sshiba** [comment]
This function has been merged in airshipctl project.
As requested, it has been added to airship-core but it has not been merged yet.

**Comment by mf4716** [comment]
@sshiba - Sidney, is there an update?  When do we think we can close this out?

**Comment by sshiba** [comment]
Rechecked the patchset and Zuul test is passing. It is ready for review.

**Comment by sshiba** [comment]
https://review.opendev.org/c/airship/treasuremap/+/779413 has been merged. This issue can be now closed.

**Comment by ak3216** [comment]
Closing per code merge
