### ISSUE TITLE
Create Manifest Function for NGINX Ingress Controller

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#24]
To support software stack deployment of an ingress controller, create a manifest function to allow delivery of NGINX Ingress Controller from treasuremap.

**Proposed change**
Utilize the flux helm operator in airshipctl (airshipit/airshipctl#177) to create a manifest function to configure NGINX Ingress Controller to a cluster.  Implement proper gating to validate delivery.

**Comment by lb4368** [comment]
Blocked by #26

**Comment by drewwalters96** [comment]
I'll start this. Hopefully the dex operator will be delivered by the time this is complete. If not, it can remain a WIP until then.

**Comment by drewwalters96** [comment]
Closed in https://github.com/airshipit/treasuremap/commit/971417cf558d748544f131017f3aedef86c925a6
