### ISSUE TITLE
Airship 2.0 Kubernetes Conformance Certification

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#25]
**Proposed change**
As a participant in the Cloud iNfrastructure Telco Task Force (CNTT), Airship needs to have Kubernetes Conformance Certification so it can meet the requirements of CNTT Reference Architecture v2.

K8s conformance information can be found here: https://www.cncf.io/certification/software-conformance/
Specifically, information executing conformance testing can be found here:
https://github.com/cncf/k8s-conformance/blob/master/instructions.md

This should be developed as a gating job (unless performance test determines this is not feasible) that can be utilized on an ongoing basis to ensure continued conformance as changes are made. The initial ask here to develop the job & test performance. It could be integrated as a step in the Airshipctl deployment once performance has been proven. 

CNTT RA2 information can be found here: https://wiki.lfnetworking.org/display/LN/CNTT+RA2+-+Kubernetes

Per @jgu17, once it has been certified, we need to get Airship added to this list: https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0.

**Comment by mattmceuen** [comment]
This has been merged (into airshipctl, change # 767392).

**Comment by ak3216** [comment]
Closing per code merge & opening of #79 & #80.
