### ISSUE TITLE
Create Manifest Function for Local Persistence Volume Static Provisioner

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#27]
To support software stack deployment of the local static volume provisioner, create a manifest function to allow delivery of Local Persistence Volume Static Provisioner (https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) from treasuremap.

Proposed change
Utilize the flux helm operator in airshipctl (airshipit/airshipctl#177) to create a manifest function to configure Local Persistence Volume Static Provisioner to a cluster. Implement proper gating to validate delivery (Depends upon #26 ).

This is currently implemented in downstream lab as a local-storage manifest function.

**Comment by lb4368** [comment]
Dependent issue #26  is closed so removing blocked label.

**Comment by kumarlakshman** [comment]
assign to me

**Comment by ak3216** [comment]
@kumarlakshman all yours. Thanks.

**Comment by ak3216** [comment]
Please ensure that this is included in the airship-core type deployment

**Comment by mf4716** [comment]
PS in review is: https://review.opendev.org/c/airship/treasuremap/+/776175
