### ISSUE TITLE
Airshipctl Integration with Rook for Deployment of Ceph Cluster

### ISSUE THREAD

**Issue by sharathrrao** [airshipit/treasuremap#30]
**Problem description (if applicable)**
Airshipctl integrates with Helm charts to deploy Ceph cluster. This implies that there is always heavy development needed to upgrade, maintain any ceph cluster. Also, due to the current structure, it make scaling the ceph cluster harder. 

**Proposed change**
As we move towards more Cloud Native way to implement the various components, we need to consider that for the storage space as well.  Rook is an Open Source Cloud Native Storage Orchestrator for k8s that provides a platform for storage solutions mainly Ceph.  Rook aids in deployment and life cycle management of Ceph. It supports self-managing, self-scaling and self-healing storage services via the rook operator. Airship 2.0 can use Rook to implement the required Ceph cluster. This will enable a cloud native implementation and aid in upgrades of the ceph cluster.

**Potential impacts**
There may be potential issues when consuming an existing ceph cluster that has been deployed via Helm and converting that into a Rook Deployment.

**Comment by ak3216** [comment]
This was moved from Airshipctl per the 8/26 Flight Plan call. Implementation has been done as a helm-release downstream in the lab. If access to the downstream implementation is required, please reach out in the Airshipit Slack/IRC.

**Comment by vs422h** [comment]
Please assign this issue to me. Thanks.

**Comment by drewwalters96** [comment]
@vs422h all yours!

**Comment by ak3216** [comment]
Please ensure that this is included in the airship-core type deployment

**Comment by mf4716** [comment]
@vs422h - Vladimir, is there an update?  When do we think we can close this out?

**Comment by lb4368** [comment]
In addition to delivering the ROOK-Ceph operator, please enhance the gating to integrate the operator in treasuremap airship-core type.

**Comment by vs422h** [comment]
The Airship Integration with Rook for Deployment of Ceph cluster has been implemented, tested upstream and downstream and merged into master branch.
https://review.opendev.org/c/airship/treasuremap/+/788487
Also some minor fixes were implemented and merged, as well. I think, we can close the issue.

**Comment by ak3216** [comment]
Closing per above.
