### ISSUE TITLE
Configure Pod Security Policy Resources

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#31]
As an operator I need to configure one or more pod security policies so that I can control conditions with which pods in my site(s) must run in order to meet security requirements of my organization.

This includes but is not limited to configuration of AppArmor and seccomp profiles used by containers.

**Comment by lb4368** [comment]
This issue may need some design discussion that may result in associated issues being created.  Some design items:

1)  PodSecurityPolicy admission controller needs to be enabled via enable-admission-plugins argument to api-server
2)  Where are default seccomp and AppArmor profiles defined?  Image Builder?
3)  What considerations are there for defining the ClusterRole and ClusterRole binding for a PSP?
4)  How will values be specified for PSP?  Will this be a manifest function?
5)  What treasuremap sites will have pre-installed PodSecurityPolicy (if any)?

**Comment by jezogwza** [comment]
refer to #86  for information on a new direction.

**Comment by ak3216** [comment]
Please ensure that this is included in the airship-core type deployment

**Comment by ak3216** [comment]
Closing per 3/10 flight plan. Work will just be done downstream for existing PSPs & will pursue #86 as the upstream solution
