### ISSUE TITLE
Apply failsafe North - South network policies via Calico chart

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#32]
As an operator, I want the ability to define the failsafe rules (GlobalNetwork policies) through a Calico chart so that bare minimum required ports are opened for specific protocols as needed to complete the site deployment successfully.

At a minimum this would disabling Calico's default failsafe parameters by setting FailsafeInboundHostPorts and FailsafeOutboundHostPorts to "none". 

In place of the default failsafe rules the following need to be defined: TBD

**Comment by manojkva** [comment]
Please assign this to me.

**Comment by ak3216** [comment]
Please ensure that this is included in the airship-core type deployment

**Comment by manojkva** [comment]
Review ready PS = https://review.opendev.org/c/airship/treasuremap/+/775557

**Comment by manojkva** [comment]
Could be closed. PS = https://review.opendev.org/c/airship/treasuremap/+/775557 merged.

**Comment by manojkva** [comment]
Could be closed.PS https://review.opendev.org/c/airship/treasuremap/+/775557 merged.

**Comment by lb4368** [comment]
Closing per comment above
