### ISSUE TITLE
Provide example open source Calico Network Policy function

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#43]
As an operator, I want an example Calico network policy function based on open source calico, so that I can have a model to apply various Calico CRs in my environment.

This has dependency on https://github.com/airshipit/airshipctl/issues/368 for the Tigera Operator integration which will be used to deploy Calico.

The example policy function should be included at the network cloud virtual test site level (not the type level), so that it doesn't load the network cloud type with example resources that are not wanted in real network cloud sites.

Samples should be based on the GlobalNetworkPolicy or NetworkPolicy custom resources.

Background on Calico network policies:
https://docs.projectcalico.org/security/calico-network-policy
https://docs.projectcalico.org/security/tutorials/kubernetes-policy-advanced

**Comment by eratnch** [comment]
I can start looking into this issue. Please assign to me.

**Comment by ak3216** [comment]
@eratnch, all yours! Thanks!

**Comment by eratnch** [comment]
I am able to deploy sample network policies (kubernetes policy and calico policy) using `initinfra-networking` as a phase for both ephemeral and target cluster.

The integration using phase commands is described [here](https://hackmd.io/RyqVceQeSpqBS3OrtsH6XQ?view).

**Comment by eratnch** [comment]
There are two different CRs supported by Calico network policies.

- One that uses `apiVersion` as `crd.projectcalico.org/v1`
- The other that uses `apiVersion` as `projectcalico.org/v3`
The first types of policies can be deployed through `kubectl` commands.
The second types of policies need to be deployed through `calicoctl`. 
Waiting on some input on whether we can use the first kind (with crd) of policies that don't need to use `calicoctl`.

**Comment by eratnch** [comment]
A WIP PS https://review.opendev.org/c/airship/treasuremap/+/774144

**Comment by eratnch** [comment]
Calico policies with CRs of types `crd.projectcalico.org/v3` or `projectcalico.org/v3`  can't be deployed with `kubectl` with Calico Opensource. One needs to use `calicoctl` to deploy these CRs. 
There's an open issue in  [projectcalico github](https://github.com/projectcalico/calico/issues/2923).

**Comment by eratnch** [comment]
Function with sample NW policies is added in [this PS](https://review.opendev.org/c/airship/treasuremap/+/776840)
Wiring the function into virtual-network-cloud site is added in [this PS](https://review.opendev.org/c/airship/treasuremap/+/776841)

**Comment by ak3216** [comment]
Please ensure that this is included in the airship-core type deployment

**Comment by teoyaomiqui** [comment]
@eratnch according to the issue you mentioned, they seem to support these configurations but with a different version:
https://github.com/projectcalico/calico/issues/2923#issuecomment-801558258

**Comment by eratnch** [comment]
> Please ensure that this is included in the airship-core type deployment

Hi @ak3216, does the n/w policy need to be included in manifest/function(as per the original description above) or only in the airship-core type? Can you please confirm. Thanks

**Comment by eratnch** [comment]
> @eratnch according to the issue you mentioned, they seem to support these configurations but with a different version:
> [projectcalico/calico#2923 (comment)](https://github.com/projectcalico/calico/issues/2923#issuecomment-801558258)

Hi @teoyaomiqui, according to the comment mentioned in the issue, kubectl only supports v1 api resources whereas n/w policies in airship is using v3 which is supported by calicoctl.

**Comment by mattmceuen** [comment]
@eratnch I'm thinking the answer would be "both":

1. Let's put the definitions in a manifest/function, so that they're findable, reusable, easily copyable.  If the manifests are reusable  in real-life deployments (my understanding is that they are) then I think the current "network-policy" function name is good; otherwise we'd want to use something like "network-policy-example"
2. The function should be kustomized in as a resource in `airship-core/target/workload` , unless @ak3216 thinks a different phase is more appropriate.

That way sites associated with, `airship-core`, `multi-tenant`, and downstream types would all inherit the foundational policy.

**Comment by ak3216** [comment]
workload works for me

**Comment by eratnch** [comment]
Thanks @mattmceuen , @ak3216.

**Comment by eratnch** [comment]
[PS](https://review.opendev.org/c/airship/treasuremap/+/778359) ready for review, thanks.

**Comment by lb4368** [comment]
@eratnch Since patchset above is merged, can this be closed?

**Comment by eratnch** [comment]
@lb4368, I think it would be good if we can merge PS https://review.opendev.org/c/airship/treasuremap/+/783131 and then close this. This is because the PS https://review.opendev.org/c/airship/treasuremap/+/783131 adds the n/w policy overrides in `multi-tenant` type as was discussed in a design discussion.

**Comment by eratnch** [comment]
@lb4368, @ak3216 this issue can be closed.

**Comment by ak3216** [comment]
Closing per above. #119 will implement the phase to deliver.
