### ISSUE TITLE
CI: Replace deprecated GitHub authentication method

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/treasuremap#44]
**Problem description (if applicable)**
An endpoint used in our post job [will no longer be supported in November](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/). In order to ensure that our jobs run successfully, we need to update our authentication method for GitHub.

**Proposed change**
Change the password authentication in [update_github_issues.py](https://github.com/airshipit/treasuremap/blob/v2/playbooks/airship-treasuremap-update-github-issues.yaml#L30) to a supported method.

**Comment by sirajyasin** [comment]
This issue is resolved with this PS
https://review.opendev.org/#/c/759453/

**Comment by jezogwza** [comment]
Close , ps was merged
