### ISSUE TITLE
Patch hostgenerators to delete catalogues

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/treasuremap#48]
To facilitate catalogue-driven generation of BareMetalHost resources, airship splits the work into two pieces:
1. `<phasename>/hostgenerator/` is responsible for substituting catalogue variables into a host generation template
2. `<phasename>/` invokes its `hostgenerator/` as a Kustomize `generator:`, leveraging the results of 1. to generate BMH.

However, a weird side-effect of this setup is that the catalogues used in step 1. above are still hanging around in step 2., and Kustomize tries to interpret them as `generator:` plugin configs, resulting in a rendering error.

Previously, we'd worked around this by having a pass-through plugin implementation, which performs a no-op generation for the spent catalogues.

However, with the change below, airshipctl migrated to container-based KRM functions for its kustomize plugins, and also adopted a strategic-patch-delete mechanism to clean up the spent catalogues, so that they aren't still hanging around by the time the generation occurs.

https://review.opendev.org/#/c/759279/

We need to true up the Treasuremap `hostgenerator/` kustomizations to do the same; as it stands they're not rendering successfully.

**Comment by drewwalters96** [comment]
Closed in https://github.com/airshipit/treasuremap/commit/39a6036ca89a53daf8482dc5f1547aed01e5e4ab
