### ISSUE TITLE
Define Treasuremap Branching Strategy

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#50]
This is a placeholder issue to review the branching strategy for treasuremap to align with the Airship 2.0 release.

Currently, we have these Treasuremap branches:
- master (Airship 1, with sloop, skiff, foundry etc)
- v1.8-prime branch (latest Airship 1, but only cruiser type functional)
- v2.0 branch (Airship 2)

One approach would be to rename the current v2 branch to main, rename the main branch to v1.7 & leave the v1.8 branch as is.

Link to the 12/10/20 design call:
https://hackmd.io/QiEksO4fRk-MnBjwBFaAkQ#Treasuremap-Branching

**Comment by matthew-fuller** [comment]
Please assign this to me.

**Comment by ak3216** [comment]
@matthew-fuller all yours

**Comment by matthew-fuller** [comment]
Added to design call agenda for 3/18.

**Comment by matthew-fuller** [comment]
Per today's design call (3/23) the following was decided:

- Move the 'v2' branch to 'master
- Move the current 'master' branch to a new 'v1.9' branch
- Keep the 'v1.8' branch as-is

These changes will occur on, or slightly after, April 1, 2021. I've created a patch for the v2 and master branches to amend the README files with a notice regarding the upcoming changes, and I'll be sending out an email to the Airship community mailing lists with the same information.

Related patches:
v2: https://review.opendev.org/c/airship/treasuremap/+/782601
master: https://review.opendev.org/c/airship/treasuremap/+/782604

**Comment by mf4716** [comment]
@matthew-fuller - both respective PSs have merged.  Okay to leave it open until the actual work is implemented?  
Related patches:
v2: https://review.opendev.org/c/airship/treasuremap/+/782601
master: https://review.opendev.org/c/airship/treasuremap/+/782604

**Comment by seaneagan** [comment]
@matthew-fuller: after the branch shuffle, we will want to move the `.github` directory content from the `v1.9` branch (back) to `master`, since that is the branch that github looks at for that metadata (issue templates, workflows).

**Comment by matthew-fuller** [comment]
Branch name changes were completed on 4/16, and the 2 changes related to moving the .github directory from v1.9 to master (https://review.opendev.org/c/airship/treasuremap/+/786763
https://review.opendev.org/c/airship/treasuremap/+/786762) have merged, completing all work for this issue.
