### ISSUE TITLE
Create airshipit/treasuremap Function for logging-operator

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#51]
Description :
As a developer I need the ability to run the logging-operator in the cluster to manage the logs. Logging operator automates the deployment and configuration of a Kubernetes Cluster logging .
For this a logging-operator function will be created in the airshipit/treasuremap repo.

Upstream reference link :  https://github.com/banzaicloud/logging-operator

Acceptance Criteria : 
- Creation of reusable logging-operator function which can be used in any cluster.

**Comment by StevTheDev** [comment]
Hello @sb1975, this function is added in [this PS](https://review.opendev.org/c/airship/treasuremap/+/769095/)

**Comment by StevTheDev** [comment]
Hello again @sb1975, the PS which added this function has [been merged](https://review.opendev.org/c/airship/treasuremap/+/769095).

**Comment by sb1975** [comment]
Closing since code merged.

**Comment by ak3216** [comment]
Please ensure that this is included in the airship-core type workload deployment
