### ISSUE TITLE
Create airshipit/treasuremap Function for Elasticsearch

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#52]
Description :
As a developer I need the ability to create an Elasticsearch function in the airshipit/treasuremap repo to create the Elasticsearch cluster used for storing logs in the cluster.

Upstream reference link :  https://github.com/elastic/helm-charts/tree/master/elasticsearch

Acceptance Criteria :

Creation of reusable Elasticsearch  function which can be used in any cluster.

**Comment by gtsteffaniak** [comment]
ssign to me

**Comment by sb1975** [comment]
PS Submitted Graham https://review.opendev.org/c/airship/treasuremap/+/771884

**Comment by ak3216** [comment]
Please ensure that this is included in the airship-core type workload deployment

**Comment by mf4716** [comment]
@gtsteffaniak - hey Graham, is there a status on this issue?

**Comment by gtsteffaniak** [comment]
@mf4716 Last week we have a working PS for this that we are hoping to merge once its ready :
https://review.opendev.org/c/airship/treasuremap/+/779915

**Comment by lb4368** [comment]
New cherry picked PS on treasuremap master:  https://review.opendev.org/c/airship/treasuremap/+/792387

**Comment by StevTheDev** [comment]
PS submitted, pending review

[Treasuremap Elasticsearch & Kibana](https://review.opendev.org/c/airship/treasuremap/+/792788)

**Comment by StevTheDev** [comment]
With that item merged, I'd say we can close this issue!
