### ISSUE TITLE
Create airshipit/treasuremap Function for Elasticsearch Exporter

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#54]
Description :
As a developer I need the ability to create an function for Elasticsearch Exporter in the airshipit/treasuremap repo to create the Elasticsearch Exporter  for integration with Prometheus.

Upstream reference link : https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter

Acceptance Criteria :

Creation of reusable elasticsearch-exporter function which can be used in any cluster.

**Comment by eratnch** [comment]
Please assign this issue to me. Thanks.

**Comment by gtsteffaniak** [comment]
assign to me please

**Comment by ak3216** [comment]
@gtsteffaniak done

**Comment by ak3216** [comment]
Please ensure that this is included in the airship-core type workload deployment

**Comment by lb4368** [comment]
PS:  https://review.opendev.org/c/airship/treasuremap/+/792396

**Comment by StevTheDev** [comment]
PS submitted, pending review

[Add elasticsearch-exporter to our elastic-stack](https://review.opendev.org/c/airship/treasuremap/+/792835)

**Comment by StevTheDev** [comment]
https://review.opendev.org/c/airship/treasuremap/+/792835

With that item merged, I'd say we can close this issue!
