### ISSUE TITLE
Create LMA-base composite in airshipit/treasuremap

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#55]
Description :
As a developer I would like to Create LMA-base composite that can be used for any Cluster.

The LMA-Base Composite will use the Logging-operator function and the Kube-Prometheus-Stack function. However the Grafana will be disabled by default when using the Kube-Prometheus-Stack function.

Acceptance Criteria :
  - Create the LMA-Base composite that can be reused for any cluster.

**Comment by StevTheDev** [comment]
This can be closed as a duplicate of #70
