### ISSUE TITLE
Create Elasticearch-Ingest composite in airshipit/treasuremap

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#57]
Description :

As a developer I need the ability to Create Elasticearch-Ingest composite
The composite will use the functions with overrides specific to the implementation for the cluster.

Acceptance Criteria :
- An instance of the Elasticsearch function, configured to deploy a set of nodes configured with the master and ingest roles

**Comment by lb4368** [comment]
Closing as this is now part of #83.
