### ISSUE TITLE
Create Elasticsearch-Data composite in airshipctl/treasuremap

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#58]
Description :

As a developer I need the ability to to create the Elasticsearch-Data composite in airshipctl/treasuremap
This will include instance of the Elasticsearch function, configured to deploy a set of nodes configured with the Data role. These nodes connect to the Elasticsearch-ingest nodes to form the Elasticsearch cluster

Acceptance Criteria :
- An instance of the Elasticsearch-Data composite using Elasticsearch function, configured to deploy a set of nodes configured with the Data role.

**Comment by lb4368** [comment]
Closing as this is now part of #83.
