### ISSUE TITLE
logging, monitoring and alerting CRs for logging-stack

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#62]
Description :

Integrate with logging-base and monitoring-base:
            1. Create logging CRs for logging-stack
            2. Create monitoring CRs for logging-stack
            3. Create alerting CRs for logging-stack
The logging,monitoring and alerting configurations specific to a cluster will be created in the coresponding CRs which will be consumed by the logging and monitoring operators.

Acceptance Criteria :
            1. Create logging CRs for logging-stack
            2. Create monitoring CRs for logging-stack
            3. Create alerting CRs for logging-stack

**Comment by lb4368** [comment]
Closing as this is now part of #83.
