### ISSUE TITLE
Create airshipit/treasuremap Functions for Kube-Prometheus-Stack

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#63]
Description: 
Create airshipit/treasuremap Functions for Kube-Prometheus-Stack for deploying the Kube-Prometheus-Stack helm charts in the cluster.

This can utilize the upstream link : 
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack.

Acceptance Criteria :
Creation of reusable Kube-Prometheus-Stack function which can be used in any cluster with composites.

**Comment by StevTheDev** [comment]
Hello @sb1975, the function is added in [this PS.](https://review.opendev.org/c/airship/treasuremap/+/769095)

**Comment by StevTheDev** [comment]
Hello again @sb1975, the PS which added this function has [been merged](https://review.opendev.org/c/airship/treasuremap/+/769095).

**Comment by sb1975** [comment]
Closed as code merged
