### ISSUE TITLE
Create airshipit/treasuremap Functions for Thanos-Operator

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#64]
Description : 
Create airshipit/treasuremap Functions for Thanos-Operator for storing the Long Term Metrics storage in a Centralized Location.

The upstream reference for Thanos operator : https://github.com/banzaicloud/thanos-operator 

Acceptance Criteria :
Creation of reusable Thanos operator function which can be used in any cluster in composites.

**Comment by sb1975** [comment]
PS Submitted Steven https://review.opendev.org/c/airship/treasuremap/+/770709)

**Comment by StevTheDev** [comment]
Please assign this one to me. Thanks!

**Comment by StevTheDev** [comment]
The PS adding this was merged on March 15th, so I believe this issue can be closed.

**Comment by lb4368** [comment]
Closing per merge of https://review.opendev.org/c/airship/treasuremap/+/770709.
