### ISSUE TITLE
Create Monitoring stack composite

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#67]
Description : Create 'Monitoring Stack' Composite
The Composite includes the following : 

- a function for deploying banzaicloud/thanos-operator
- a composite which deploys grafana and a thanos querier,
- and phase documents for running this composite in the target cluster

This change adds the 'lma-stack' phase as an entrypoint, which
can be extended to provision other lma services

**Comment by sb1975** [comment]
This is being addressed by https://review.opendev.org/c/airship/treasuremap/+/770709

**Comment by StevTheDev** [comment]
Please assign this one to me. Thanks!

**Comment by StevTheDev** [comment]
Happy to say that [the PS](https://review.opendev.org/c/airship/treasuremap/+/770709) has merged!
