### ISSUE TITLE
Create MinIO S3 Provider function

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#68]
Description : 
Create MinIO S3 Provider function in airshipit/treasuremap which can be reused in Composites for creating Object Storage.

Acceptance Criteria : 
Creation of a reusable MinIO S3 Provider function in airshipit/treasuremap

**Comment by sb1975** [comment]
PS WIP Steven https://review.opendev.org/c/airship/treasuremap/+/770710

**Comment by StevTheDev** [comment]
Please assign this one to me. Thanks!

**Comment by sb1975** [comment]
PS Merged - https://review.opendev.org/c/airship/treasuremap/+/770710
