### ISSUE TITLE
Create LMA-Storage (Minio) composite

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#69]
Description : 
Create LMA-Storage (Minio) composite to address the Object storage requirement for the LMA subcluster needs.
MinIO will get deployed and will provide the object buckets for LMA components like Elasticsearch snapshots.

This is being addressed by PS: https://review.opendev.org/c/airship/treasuremap/+/770710

**Comment by StevTheDev** [comment]
Please assign this one to me. Thanks!

**Comment by StevTheDev** [comment]
[This patchset was merged on march 15](https://review.opendev.org/c/airship/treasuremap/+/770710).

**Comment by lb4368** [comment]
Closing per patchset merge
