### ISSUE TITLE
Error : Trying to build Airship2 using Treasuremap

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#73]
When I run the below 
user@airship:~/treasuremap$ sudo tools/deployment/22_test_configs.sh

It gives error , can someone please fix or add more explanation why its happening in Treasuremap ? (While similar script works in Airshipctl)

+ airshipctl config set-manifest treasuremap --repo airshipctl --url https://opendev.org/airship/airshipctl.git --commithash 1890d0cd7e9b868c3afdc8d1c65713e739dc9da2
Manifest "treasuremap" created.
+ airshipctl config set-manifest treasuremap --repo treasuremap --url /home/user/treasuremap --commithash 36226214e5c45a8ce5f82697ba2521922f0389ef airshipctl config set-context ephemeral-cluster --manifest treasuremap
unknown flag: --manifest

**Comment by sb1975** [comment]
This was due to a "/" after the command in Line 45.
Reference - https://review.opendev.org/c/airship/treasuremap/+/768568/2/tools/deployment/22_test_configs.sh#45

**Comment by sb1975** [comment]
Noe getting error in next step : 

> esudbat@airship:~/treasuremap$ sudo ./tools/deployment/23_pull_documents.sh
+ airshipctl document pull --debug
[airshipctl] 2021/01/05 15:54:23 opendev.org/airship/airshipctl@/pkg/document/pull/pull.go:36: Reading current context manifest information from /home/esudbat/.airship/config
[airshipctl] 2021/01/05 15:54:23 opendev.org/airship/airshipctl@/pkg/document/pull/pull.go:51: Downloading airshipctl repository airshipctl from https://opendev.org/airship/airshipctl.git into /tmp/default
[airshipctl] 2021/01/05 15:54:23 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:141: Attempting to download the repository airshipctl
[airshipctl] 2021/01/05 15:54:23 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:126: Attempting to clone the repository airshipctl from https://opendev.org/airship/airshipctl.git
[airshipctl] 2021/01/05 15:54:27 opendev.org/airship/airshipctl@/pkg/document/repo/repo.go:110: Attempting to checkout the repository airshipctl from commit hash 1016a29870f19c0b783e93f8717bb92e7555f1ac
Repository spec requires url.

**Comment by sb1975** [comment]
The next error : 
```

$ sudo ./tools/deployment/25_deploy_ephemeral_node.sh
+ : ../airshipctl
+ cd ../airshipctl
+ ./tools/deployment/25_deploy_ephemeral_node.sh
+ export TIMEOUT=3600
+ TIMEOUT=3600
+ export KUBECONFIG=/home/user/.airship/kubeconfig
+ KUBECONFIG=/home/user/.airship/kubeconfig
+ export KUBECONFIG_EPHEMERAL_CONTEXT=ephemeral-cluster
+ KUBECONFIG_EPHEMERAL_CONTEXT=ephemeral-cluster
+ echo 'Deploy ephemeral node using redfish with iso'
Deploy ephemeral node using redfish with iso
+ airshipctl baremetal remotedirect --debug
[airshipctl] 2021/01/05 17:17:30 opendev.org/airship/airshipctl@/pkg/remote/management.go:202: Remote type: Redfish
[airshipctl] 2021/01/05 17:17:35 opendev.org/airship/airshipctl@/pkg/remote/remote_direct.go:67: Bootstrapping ephemeral host 'node02' with ID 'air-ephemeral' and BMC Address 'redfish+https://localhost:8443/redfish/v1/Systems/air-ephemeral'.
redfish client encountered an error: HTTP request failed. Redfish may be temporarily unavailable. Please try again.
```

**Comment by sb1975** [comment]
Error at next level :
```
sb0601@airship:~/treasuremap$ sudo ./tools/deployment/31_deploy_initinfra_target_node.sh
+ export KUBECONFIG=/home/sb0601/.airship/kubeconfig
+ KUBECONFIG=/home/sb0601/.airship/kubeconfig
+ NODENAME=node01
+ export KUBECONFIG_TARGET_CONTEXT=target-cluster
+ KUBECONFIG_TARGET_CONTEXT=target-cluster
+ : ../airshipctl
+ cd ../airshipctl
+ kubectl --kubeconfig /home/sb0601/.airship/kubeconfig --context target-cluster --request-timeout 10s label node node01 node-type=controlplane
Unable to connect to the server: dial tcp 10.23.25.102:6443: connect: no route to host

```

**Comment by lb4368** [comment]
@sb1975 Is there still an issue here?  Can this be closed?

**Comment by sb1975** [comment]
Didnt check recently, will close for now.
