### ISSUE TITLE
Explanation on .airship/config file

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#74]
It would be helpful to understand the use of "airshipctl document pull" and how it works together with the content of the .airship/config.

`apiVersion: airshipit.org/v1alpha1
contexts:
  default:
    contextKubeconf: ""
    managementConfiguration: default
    manifest: default
  ephemeral-cluster:
    contextKubeconf: ephemeral-cluster_ephemeral
    managementConfiguration: dummy_management_config
    manifest: treasuremap
  target-cluster:
    contextKubeconf: target-cluster_target
    managementConfiguration: dummy_management_config
    manifest: treasuremap
currentContext: ephemeral-cluster
encryptionConfigs: null
kind: Config
managementConfiguration:
  default:
    systemActionRetries: 30
    systemRebootDelay: 30
    type: redfish
  dummy_management_config:
    insecure: true
    systemActionRetries: 30
    systemRebootDelay: 30
    type: redfish
manifests:
  default:
    metadataPath: manifests/site/test-site/metadata.yaml
    phaseRepositoryName: primary
    repositories:
      primary:
        checkout:
          branch: master
          commitHash: ""
          force: false
          tag: ""
        url: https://opendev.org/airship/treasuremap
    targetPath: /tmp/default
  dummy_manifest:
    metadataPath: /manifests/site/test-site/metadata.yaml
    phaseRepositoryName: primary
    repositories:
      primary:
`
It would be helpful to understand the parameters and how these need to be modified for 
1. Any new Site Deployment
2. How to use it for testing any new function/composite in Treasuremap.

**Comment by ermurugesanbe** [comment]
please assign to me

**Comment by ermurugesanbe** [comment]
Submitted PS https://review.opendev.org/c/airship/airshipctl/+/812347/

**Comment by dinesh14nish** [comment]
PS https://review.opendev.org/c/airship/airshipctl/+/812347/ merged.

**Comment by dinesh14nish** [comment]
Please close this.

**Comment by eak13** [comment]
Closing per merge
