### ISSUE TITLE
Treasuremap needs to be updated to use Tigera Operator

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/treasuremap#75]
Recently, airshipctl migrated from raw calico manifests to using the tigera operator to install calico.  This had impacts to the manifests:
https://review.opendev.org/c/airship/airshipctl/+/762773

Since Treasuremap uses airshipctl's deployment scripts, which have a dependency now on tigera operator, we should go ahead and make the same changes to treasuremap's airship-core type which were made to airshipctl's test-site in the change above.

**Comment by sirajyasin** [comment]
I can start looking into this issue.

**Comment by drewwalters96** [comment]
Thanks @sirajyasin

**Comment by sirajyasin** [comment]
https://review.opendev.org/c/airship/treasuremap/+/769412

**Comment by sirajyasin** [comment]
The PS https://review.opendev.org/c/airship/treasuremap/+/769412 to fix calico deployment is merged. This issue can be marked closed

**Comment by sirajyasin** [comment]
This issue can be marked closed.

**Comment by ak3216** [comment]
Closing per code merge.
