### ISSUE TITLE
Deploy worker node is failing due to recent changes in arishipctl

### ISSUE THREAD

**Issue by sirajyasin** [airshipit/treasuremap#77]
**Describe the bug**
Deploy worker node is failing due to recent changes in arishipctl folder structure. A new director provision created within test-site/target/worker.

**Steps To Reproduce**
Deploy test-site using treasuremap v2

**Expected behavior**
Deployment of worker node should be successful.

**Environment**
- airshipctl Version:
- Operating System:
- Kernel version:
- Kubernetes Version:
- Go version:
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):

**Comment by sirajyasin** [comment]
@ak3216 , After the recent manifest alignment with airshipctl, test-site deployment is validated in Third party gating and in local dev setup. So this issue can be marked completed.

**Comment by ak3216** [comment]
Closing per recent updates noted above.
