### ISSUE TITLE
Reuse phase, executor, and plan definitions from airshipctl

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/treasuremap#78]
The [Treasuremap phase definitions ](https://github.com/airshipit/treasuremap/tree/v2/manifests/type/airship-core/phases) in each type are identical to the ones in airshipctl yet they are redefined. Rather than redefining the phases, we should inherit all phases from airshipctl and patch them when necessary.

**Comment by sirajyasin** [comment]
I can start working on this issue if no one has started yet

**Comment by sirajyasin** [comment]
PS in review
https://review.opendev.org/c/airship/treasuremap/+/772756

**Comment by sirajyasin** [comment]
This issue can be closed as the related PS ( https://review.opendev.org/c/airship/treasuremap/+/772756) is merged

**Comment by ak3216** [comment]
closing per code merge
