### ISSUE TITLE
Create Sub-Cluster Manifest Type/Functions

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#82]
As an operator, I want sub-cluster manifest type and/or functions define base artifacts deploying sub-cluster components, so that I have a template for the stages of sub-cluster deployment and better and easier management of the deployment artifacts.

These should be defined so that they can then be inherited/called and customized using replacement transformation in sites to achieve the required configuration for the sub-clusters.

The base sub-cluster phases defined in treasuremap type/functions include the following:

- provide-infra - delivers the SIP CR containing sub-cluster and associated infrastructure services configuration
- control-plane - CAPI control plane for the sub-cluster
- workers - CAPI data plane for the sub-cluster
- initinfra - Delivers infrastructure common to all sub-clusters (e.g. Helm Operator, Stack, Logging Operator, CNI, Storage classes etc.)

**Comment by sshiba** [comment]
I can work on this issue if no one has done it yet. Please, let me know if I can be assigned to this issue.

**Comment by ak3216** [comment]
@sshiba all yours. Please make sure you let us know the tshirt size so we can add the label. Thanks!

**Comment by sshiba** [comment]
Is that ok to say Large as not sure the effort level yet? Will give a better estimation later.

**Comment by ak3216** [comment]
@sshiba that's fine. We can always tweak as needed. Set to lg for now

**Comment by drewwalters96** [comment]
@sshiba and I talked offline, and I will take this issue so that he can focus his full attention on the implementation of Dex. I will also work this with #107

**Comment by pramchan** [comment]
Is Sub-Cluster  ha aware? - Referring to https://review.opendev.org/c/airship/treasuremap/+/779889/20

**Comment by drewwalters96** [comment]
Completed in https://review.opendev.org/c/airship/treasuremap/+/780910
