### ISSUE TITLE
Create Elastic-Stack composite 

### ISSUE THREAD

**Issue by sb1975** [airshipit/treasuremap#83]
This Issue combines the following Issues :
    # Create Elasticsearch Exporter composite #60
    # Create Kibana composite in airshipctl/treasuremap #59
    # Create Elasticsearch-Data composite in airshipctl/treasuremap #58
    # Create Elasticearch-Ingest composite in airshipit/treasuremap #57
    # logging, monitoring and alerting CRs for logging-stack #62

This is addressed by the below PS: 
https://review.opendev.org/c/airship/treasuremap/+/771894

**Comment by StevTheDev** [comment]
This issue is WIP in the following PS:
- [Elasticsearch & Kibana Function Manifests](https://review.opendev.org/c/airship/treasuremap/+/771884)
- [Elasticsearch Ingest/Data Composite](https://review.opendev.org/c/airship/treasuremap/+/771894)
- Elasticsearch Exporter #60

**Comment by ak3216** [comment]
These functions should be included as part of the airship-core type workload

**Comment by gtsteffaniak** [comment]
Main PS https://review.opendev.org/c/airship/treasuremap/+/790437

**Comment by StevTheDev** [comment]
These PS are submitted, pending review:

[Treasuremap Elasticsearch & Kibana](https://review.opendev.org/c/airship/treasuremap/+/792788)
[Add elasticsearch-exporter to our elastic-stack](Add elasticsearch-exporter to our elastic-stack)

**Comment by StevTheDev** [comment]
With both of those items merged, I'd say we can close this issue!
