### ISSUE TITLE
PSP are been deprecated . What is airship security posture replacement?

### ISSUE THREAD

**Issue by jezogwza** [airshipit/treasuremap#86]
PSP was found to never do what we expected anyway, but now that they are going away in k8s 1.22.

How will airship provide  the configuration to enable the security posture we want to achieve,

**Comment by lb4368** [comment]
Design approach for using [Gatekeeper] as a PSP replacement: 
- [ ] #167 
- [ ] #174 
- [ ] Define PSP-like replacement constraints

[Gatekeeper]: https://open-policy-agent.github.io/gatekeeper/website/docs/

**Comment by jezogwza** [comment]
We will be leveraging gatekeeper constraints to implement this. This issue can be closed, and for follow up you can refer to the gatekeepr issues mentioned above.
