### ISSUE TITLE
Keepalived VRRP for K8s Ingress over host management/OAM interface

### ISSUE THREAD

**Issue by onlysource** [airshipit/treasuremap#94]
**Problem description (if applicable)**
Network Cloud

**Proposed change**
Currently, k8s service-vips are dependent on  CNI to announce over BGP. Moving away this service-vip to the management (OAM) interface could be ideal, eliminating any CNI dependency. The service-vips can be configured as floating-ip between all K8s master nodes, with VRRP.

**Potential impacts**
Potential security or performance related impacts.

**Comment by manojkva** [comment]
Please assign to me. Thanks

**Comment by ak3216** [comment]
@manojkva all yours. Please make sure you provide a t-shirt size once you have a chance to take a look & we'll update. Thanks!

**Comment by mf4716** [comment]
@manojkva - Manoj, per our Tech Dive today, are we close(r) to finishing this issue?  Please lean in to ensure we close this issue ASAP.

**Comment by manojkva** [comment]
Review ready PS = https://review.opendev.org/c/airship/treasuremap/+/778953

**Comment by mf4716** [comment]
PS has been merged.  @ak3216 , @manojkva  can this issue be closed?

**Comment by manojkva** [comment]
Closes: #94

**Comment by manojkva** [comment]
Yes. It could be closed.

**Comment by ak3216** [comment]
Closing per above
