### ISSUE TITLE
Align Treasuremap with recent Airshipctl changes

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#95]
Need to align Treasuremap manifests to support recent changes to airshipctl for secret encryption/decryption as part of https://github.com/airshipit/airshipctl/issues/379.

Dependent airshipctl changes:
https://review.opendev.org/c/airship/airshipctl/+/766484
https://review.opendev.org/c/airship/airshipctl/+/773730

**Comment by sirajyasin** [comment]
@ak3216 
I can work on this issue. can you please assign this to me

**Comment by sirajyasin** [comment]
@ak3216 , Treasuremap is aligned with latest ( Till Feb 26th ) airshipctl and deployment is tested working in jenkins and local setup using this PS https://review.opendev.org/c/airship/treasuremap/+/770446

There is another issue to create version pinning for airshipctl in treasuremap. So this can be marked closed.

**Comment by ak3216** [comment]
Closing per updates that Treasuremap has been synced thru 2/26.
