### ISSUE TITLE
Deployment of test-site fails in treasuremap

### ISSUE THREAD

**Issue by eratnch** [airshipit/treasuremap#96]
**Describe the bug**
The job `airship-treasuremap-deploy-test-site` fails with below error

```set -e
kustomize build --enable_alpha_plugins  src/opendev.org/airship/treasuremap/manifests/site/test-site/ephemeral/controlplane 2>/dev/null |
kustomize cfg grep  "kind=BareMetalHost"
```
The error appears to be originated from the the task `https://github.com/airshipit/treasuremap/blob/v2/playbooks/get-vm-config.yaml` and the following shell command fails in zuul.

```
shell: |
    set -e
    kustomize build --enable_alpha_plugins \
      {{ airship_config_manifest_directory }}/{{ airship_config_site_path }}/{{ path }} 2>/dev/null |
    kustomize cfg grep  "kind=BareMetalHost"
```

**Steps To Reproduce**
The job `airship-treasuremap-deploy-test-site` is triggered when a new PS is pushed to treasuremap repo. 

**Expected behavior**
The job should run without error and test-site should be deployed successfully

**Environment**
- airshipctl Version: v0.1.0
- Operating System:  Ubuntu 18.04.5 LTS
- Kubernetes Version: 1.18.6
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM): VM with 4vCPUs, 16 GB RAM

**Comment by ak3216** [comment]
@sirajyasin is this the same issue you're dealing with in #95 or something new? Thanks.

**Comment by sirajyasin** [comment]
@ak3216 , yes it is related. But we also had other failures with worker and workload for which i have open PS (https://review.opendev.org/c/airship/treasuremap/+/770446).

But for this to proceed we need to resolve issue #95 first.

**Comment by sirajyasin** [comment]
@ak3216 , This issue also can be marked closed. Now that we have success deployment of treasuremap(tes-site) with commit locked versions of airshipctl.

**Comment by lb4368** [comment]
Closing per above comment
