### ISSUE TITLE
Rename network-cloud type to multi-tenant type

### ISSUE THREAD

**Issue by ak3216** [airshipit/treasuremap#97]
In an effort to include sub-cluster support functions, the network-core type needs to be renamed multi-tenant and all impacted manifests should be updated to reference multi-tenant vs. network-cloud. 

A new network-cloud type will be created in the future which will provide Open Stack Helm support but will not necessarily include the sub-cluster functionality. 

https://github.com/airshipit/treasuremap/tree/v2/manifests/type/network-cloud

**Comment by manojkva** [comment]
Please assign it to me. Thanks

**Comment by ak3216** [comment]
@manojkva all yours!

**Comment by manojkva** [comment]
Fix : https://review.opendev.org/c/airship/treasuremap/+/777526

**Comment by lb4368** [comment]
@manojkva - Patchset is merged.  Can we close this issue?

**Comment by lb4368** [comment]
Patchset merged so closing.
