### ISSUE TITLE
Include hostconfig-operator in airship-core type

### ISSUE THREAD

**Issue by lb4368** [airshipit/treasuremap#99]
**Proposed change**
The hostconfig-operator manifest function should be included as part of the airship-core type manifest.  The host-config-operator manifest function is currently included directly from the test-site target initinfra phase manifests.  It should be included as part of the airship-core manifest type's target initinfra phase so that sites inheriting the airship-core type will include the hostconfig-operator.

**Comment by eratnch** [comment]
[Here's](https://review.opendev.org/c/airship/treasuremap/+/777665) the PS that addresses this issue.

**Comment by lb4368** [comment]
@eratnch I am assigning this to you since you have created the patch set for this.  Would you please assign a size of effort for this?  S/M/L

**Comment by eratnch** [comment]
@lb4368 thanks.
Size should be S.

**Comment by ak3216** [comment]
closing as a dupe of #99 and nginx & tigera already part of airship-core

**Comment by ak3216** [comment]
closed wrong issue

**Comment by lb4368** [comment]
PS https://review.opendev.org/c/airship/treasuremap/+/777665 is merged.  Closing this.
